//! Keyboard input handling for the terminal emulator.
//!
//! This module provides [`keystroke_to_bytes`], which converts GPUI keyboard
//! events into terminal escape sequences that can be written to the PTY.
//!
//! # Key Mappings
//!
//! ## Special Keys
//!
//! | Key | Sequence | Notes |
//! |-----|----------|-------|
//! | Enter | `\r` (0x0D) | Carriage return |
//! | Escape | `\x1b` (0x1B) | ESC |
//! | Backspace | `\x7f` (0x7F) | DEL |
//! | Tab | `\t` (0x09) | Horizontal tab |
//! | Shift+Tab | `\x1b[Z` | Backtab |
//! | Space | ` ` (0x20) | Space |
//! | Ctrl+Space | `\x00` | NUL |
//!
//! ## Arrow Keys
//!
//! Arrow key sequences depend on application cursor mode:
//!
//! | Key | Normal Mode | App Cursor Mode |
//! |-----|-------------|-----------------|
//! | Up | `\x1b[A` | `\x1bOA` |
//! | Down | `\x1b[B` | `\x1bOB` |
//! | Right | `\x1b[C` | `\x1bOC` |
//! | Left | `\x1b[D` | `\x1bOD` |
//!
//! ## Navigation Keys
//!
//! | Key | Sequence |
//! |-----|----------|
//! | Home | `\x1b[H` |
//! | End | `\x1b[F` |
//! | PageUp | `\x1b[5~` |
//! | PageDown | `\x1b[6~` |
//! | Insert | `\x1b[2~` |
//! | Delete | `\x1b[3~` |
//!
//! ## Function Keys
//!
//! | Key | Sequence |
//! |-----|----------|
//! | F1-F4 | `\x1bOP` - `\x1bOS` |
//! | F5-F12 | `\x1b[15~` - `\x1b[24~` |
//!
//! ## Control Combinations
//!
//! Ctrl+A through Ctrl+Z map to ASCII control characters 0x01-0x1A:
//!
//! | Combination | Byte |
//! |-------------|------|
//! | Ctrl+A | 0x01 |
//! | Ctrl+C | 0x03 (interrupt) |
//! | Ctrl+D | 0x04 (EOF) |
//! | Ctrl+Z | 0x1A (suspend) |
//!
//! ## Alt Combinations
//!
//! Alt+key sends ESC followed by the key: `\x1b` + key
//!
//! # Terminal Mode Effects
//!
//! The [`TermMode`] flags affect key sequences:
//!
//! - **APP_CURSOR**: Changes arrow key sequences from CSI to SS3 format
//!
//! # Example
//!
//! ```
//! use gpui::Keystroke;
//! use alacritty_terminal::term::TermMode;
//! use orcashell_terminal_view::input::keystroke_to_bytes;
//!
//! // Enter key
//! let keystroke = Keystroke::parse("enter").unwrap();
//! assert_eq!(keystroke_to_bytes(&keystroke, TermMode::empty()), Some(b"\r".to_vec()));
//!
//! // Ctrl+C (interrupt)
//! let keystroke = Keystroke::parse("ctrl-c").unwrap();
//! assert_eq!(keystroke_to_bytes(&keystroke, TermMode::empty()), Some(vec![0x03]));
//! ```

use std::io::Write;

use alacritty_terminal::term::TermMode;
use gpui::{Keystroke, Modifiers};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// Kitty keyboard protocol event types (REPORT_EVENT_TYPES).
///
/// When `TermMode::REPORT_EVENT_TYPES` is active, the event type is appended
/// to the modifier parameter with a `:` separator in escape-encoded sequences.
/// Press (1) is the default and is always omitted on the wire.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KeyEventType {
    Press = 1,
    Repeat = 2,
    Release = 3,
}

/// Input event context for keyboard encoding.
///
/// Wraps a GPUI `Keystroke` with additional metadata needed for extended
/// Kitty keyboard protocol features (event types, associated text).
#[derive(Clone, Debug)]
pub struct KeyInput<'a> {
    pub keystroke: &'a Keystroke,
    pub event_type: KeyEventType,
    /// The text actually generated by this key event (from GPUI's `key_char`).
    /// Used for `REPORT_ASSOCIATED_TEXT` (Kitty level 5).
    pub associated_text: Option<&'a str>,
}

// ---------------------------------------------------------------------------
// Kitty modifier-key codepoints
// ---------------------------------------------------------------------------

/// Left Shift (GPUI doesn't distinguish left/right).
pub const KITTY_LEFT_SHIFT: u32 = 57441;
/// Left Control.
pub const KITTY_LEFT_CONTROL: u32 = 57442;
/// Left Alt / Option.
pub const KITTY_LEFT_ALT: u32 = 57443;
/// Left Super / Cmd.
pub const KITTY_LEFT_SUPER: u32 = 57444;
/// Caps Lock.
pub const KITTY_CAPS_LOCK: u32 = 57358;

// ---------------------------------------------------------------------------
// Modifier encoding
// ---------------------------------------------------------------------------

/// Compute the Kitty keyboard protocol modifier bitmask from GPUI modifiers.
///
/// Kitty spec bitmask: shift=1, alt=2, ctrl=4, super=8.
/// Returns 0 if no modifiers are active. The wire format sends `mask + 1`,
/// but this function returns the raw mask.
pub fn kitty_modifier_mask(modifiers: &Modifiers) -> u8 {
    let mut mask = 0u8;
    if modifiers.shift {
        mask |= 1;
    }
    if modifiers.alt {
        mask |= 2;
    }
    if modifiers.control {
        mask |= 4;
    }
    if modifiers.platform {
        mask |= 8;
    }
    mask
}

// ---------------------------------------------------------------------------
// CSI encoding helpers
// ---------------------------------------------------------------------------

/// Write the modifier+event_type sub-parameter: `{mods+1}` or `{mods+1}:{event_type}`.
///
/// Kitty spec rules:
/// - Press (1) is the default and is always omitted.
/// - If mods==0 and event_type==Press, the whole modifier param can be omitted
///   (caller decides whether to emit the `;`).
/// - If mods==0 but event_type is Repeat/Release, we must emit `1:{type}`
///   because the modifier field hosts the event-type sub-parameter.
fn write_mods_and_event(buf: &mut Vec<u8>, mods: u8, event_type: Option<KeyEventType>) {
    write!(buf, "{}", (mods as u16) + 1).unwrap();
    if let Some(et) = event_type {
        if !matches!(et, KeyEventType::Press) {
            write!(buf, ":{}", et as u8).unwrap();
        }
    }
}

/// Returns true if the modifier+event_type portion is non-trivial (needs emitting).
fn has_mod_or_event(mods: u8, event_type: Option<KeyEventType>) -> bool {
    mods > 0
        || matches!(
            event_type,
            Some(KeyEventType::Repeat) | Some(KeyEventType::Release)
        )
}

/// Encode associated text as colon-separated Unicode codepoints.
fn write_associated_text(buf: &mut Vec<u8>, text: &str) {
    for (i, ch) in text.chars().enumerate() {
        if i > 0 {
            buf.push(b':');
        }
        write!(buf, "{}", ch as u32).unwrap();
    }
}

/// Full Kitty CSI-u encoding: `\x1b[{codepoint};{mods+1}:{event_type};{text_codepoints}u`
///
/// Omits trailing parameters when they are at their default values.
/// Release events never include associated text.
fn encode_csi_u_full(
    codepoint: u32,
    mods: u8,
    event_type: Option<KeyEventType>,
    associated_text: Option<&str>,
) -> Vec<u8> {
    // Release events never include associated text per spec.
    let text = if matches!(event_type, Some(KeyEventType::Release)) {
        None
    } else {
        associated_text.filter(|t| !t.is_empty())
    };

    let has_mods = has_mod_or_event(mods, event_type);
    let has_text = text.is_some();

    let mut buf = Vec::with_capacity(24);
    buf.extend_from_slice(b"\x1b[");
    write!(buf, "{}", codepoint).unwrap();

    if has_mods || has_text {
        buf.push(b';');
        // Only write the modifier+event_type sub-param if there's something to report.
        // When mods=0 and event_type=Press but text follows, leave the field empty
        // so the encoding is `CSI codepoint;;text u`.
        if has_mods {
            write_mods_and_event(&mut buf, mods, event_type);
        }
    }
    if has_text {
        buf.push(b';');
        write_associated_text(&mut buf, text.unwrap());
    }
    buf.push(b'u');
    buf
}

/// Encode a letter-terminated functional key: `\x1b[1;{mods+1}:{event_type}{suffix}`
///
/// Used for arrows (A/B/C/D), home (H), end (F), F1-F4 (P/Q/R/S).
fn encode_csi_modified_letter_full(
    suffix: char,
    mods: u8,
    event_type: Option<KeyEventType>,
) -> Vec<u8> {
    let mut buf = Vec::with_capacity(16);
    buf.extend_from_slice(b"\x1b[1;");
    write_mods_and_event(&mut buf, mods, event_type);
    buf.push(suffix as u8);
    buf
}

/// Simple letter-terminated encoding (backward-compat wrapper).
fn encode_csi_modified_letter(suffix: char, mods: u8) -> Vec<u8> {
    encode_csi_modified_letter_full(suffix, mods, None)
}

/// Encode a tilde-terminated functional key: `\x1b[{num};{mods+1}:{event_type}~`
///
/// Used for pageup/down (5/6), insert/delete (2/3), F5-F12.
fn encode_csi_modified_tilde_full(num: u32, mods: u8, event_type: Option<KeyEventType>) -> Vec<u8> {
    let mut buf = Vec::with_capacity(16);
    write!(buf, "\x1b[{};", num).unwrap();
    write_mods_and_event(&mut buf, mods, event_type);
    buf.push(b'~');
    buf
}

/// Simple tilde-terminated encoding (backward-compat wrapper).
fn encode_csi_modified_tilde(num: u32, mods: u8) -> Vec<u8> {
    encode_csi_modified_tilde_full(num, mods, None)
}

/// Encode a modifier-only key press/release for the Kitty protocol.
///
/// Used by `terminal_view.rs` when handling `ModifiersChangedEvent` to report
/// modifier key events (shift, ctrl, alt, super) to applications that request
/// `REPORT_ALL_KEYS_AS_ESC` + `REPORT_EVENT_TYPES`.
pub fn modifier_key_to_bytes(
    codepoint: u32,
    mods: u8,
    event_type: KeyEventType,
    mode: TermMode,
) -> Option<Vec<u8>> {
    if !mode.contains(TermMode::REPORT_EVENT_TYPES) {
        return None;
    }
    let et = if matches!(event_type, KeyEventType::Press) {
        None
    } else {
        Some(event_type)
    };
    Some(encode_csi_u_full(codepoint, mods, et, None))
}

/// Convert a [`KeyInput`] to terminal escape sequence bytes.
///
/// This is the primary encoding function supporting the full Kitty keyboard
/// protocol including `REPORT_EVENT_TYPES` and `REPORT_ASSOCIATED_TEXT`.
///
/// **Critical semantics:** `REPORT_EVENT_TYPES` does NOT promote text keys to
/// CSI-u. Event type annotations (`:2` repeat, `:3` release) can only be
/// attached to keys that are already escape-encoded by another mode flag.
/// Text-producing keys stay as plain UTF-8 unless `REPORT_ALL_KEYS_AS_ESC`
/// is also active (per Kitty spec / VTE `ansi.rs:767-769`).
pub fn key_input_to_bytes(input: &KeyInput, mode: TermMode) -> Option<Vec<u8>> {
    let keystroke = input.keystroke;
    let report_event_types = mode.contains(TermMode::REPORT_EVENT_TYPES);
    let report_associated_text = mode.contains(TermMode::REPORT_ASSOCIATED_TEXT);

    // Pre-process event type: None means Press (default, omitted on wire).
    // Without REPORT_EVENT_TYPES, Release produces no output and Repeat is
    // treated as Press.
    let effective_et = if report_event_types {
        match input.event_type {
            KeyEventType::Press => None,
            other => Some(other),
        }
    } else {
        if matches!(input.event_type, KeyEventType::Release) {
            return None;
        }
        None
    };

    // Pre-process associated text.
    let effective_text = if report_associated_text {
        input.associated_text.filter(|t| !t.is_empty())
    } else {
        None
    };

    // -----------------------------------------------------------------------
    // Kitty keyboard protocol encoding
    // -----------------------------------------------------------------------
    let kitty_disambiguate = mode.contains(TermMode::DISAMBIGUATE_ESC_CODES);
    let kitty_all_keys = mode.contains(TermMode::REPORT_ALL_KEYS_AS_ESC);

    if kitty_disambiguate || kitty_all_keys {
        let mods = kitty_modifier_mask(&keystroke.modifiers);
        let has_mods = mods != 0;
        let use_csi_u = kitty_all_keys || has_mods;

        // Functional keys get event annotations even without keyboard modifiers,
        // because they are naturally escape-encoded (CSI sequences).
        let functional_annotate = has_mods || effective_et.is_some();

        // A) Special keys with Kitty codepoints (CSI-u format).
        // Associated text is omitted for enter/escape/backspace/tab. Their codepoint
        // already encodes the text, and Kitty itself omits it for these keys. Space
        // passes effective_text since it produces a printable character.
        match keystroke.key.as_str() {
            "enter" if use_csi_u => return Some(encode_csi_u_full(13, mods, effective_et, None)),
            "escape" if use_csi_u => return Some(encode_csi_u_full(27, mods, effective_et, None)),
            "backspace" if use_csi_u => {
                return Some(encode_csi_u_full(127, mods, effective_et, None))
            }
            "tab" if use_csi_u => return Some(encode_csi_u_full(9, mods, effective_et, None)),
            "space" if use_csi_u => {
                return Some(encode_csi_u_full(32, mods, effective_et, effective_text))
            }

            // B) Functional keys - CSI modified form with event type annotation.
            // Guard is expanded: has_mods OR need event annotation (repeat/release).
            "up" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('A', mods, effective_et))
            }
            "down" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('B', mods, effective_et))
            }
            "right" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('C', mods, effective_et))
            }
            "left" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('D', mods, effective_et))
            }

            "home" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('H', mods, effective_et))
            }
            "end" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('F', mods, effective_et))
            }
            "insert" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(2, mods, effective_et))
            }
            "delete" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(3, mods, effective_et))
            }
            "pageup" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(5, mods, effective_et))
            }
            "pagedown" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(6, mods, effective_et))
            }

            "f1" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('P', mods, effective_et))
            }
            "f2" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('Q', mods, effective_et))
            }
            "f3" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('R', mods, effective_et))
            }
            "f4" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('S', mods, effective_et))
            }
            "f5" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(15, mods, effective_et))
            }
            "f6" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(17, mods, effective_et))
            }
            "f7" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(18, mods, effective_et))
            }
            "f8" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(19, mods, effective_et))
            }
            "f9" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(20, mods, effective_et))
            }
            "f10" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(21, mods, effective_et))
            }
            "f11" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(23, mods, effective_et))
            }
            "f12" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(24, mods, effective_et))
            }
            "f13" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(25, mods, effective_et))
            }
            "f14" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(26, mods, effective_et))
            }
            "f15" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(28, mods, effective_et))
            }
            "f16" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(29, mods, effective_et))
            }
            "f17" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(31, mods, effective_et))
            }
            "f18" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(32, mods, effective_et))
            }
            "f19" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(33, mods, effective_et))
            }
            "f20" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(34, mods, effective_et))
            }
            // F21-F35: use Kitty codepoints in CSI-u format (no standard legacy tilde codes)
            "f21" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 8, mods, effective_et, None))
            }
            "f22" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 9, mods, effective_et, None))
            }
            "f23" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 10, mods, effective_et, None))
            }
            "f24" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 11, mods, effective_et, None))
            }
            "f25" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 12, mods, effective_et, None))
            }
            "f26" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 13, mods, effective_et, None))
            }
            "f27" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 14, mods, effective_et, None))
            }
            "f28" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 15, mods, effective_et, None))
            }
            "f29" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 16, mods, effective_et, None))
            }
            "f30" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 17, mods, effective_et, None))
            }
            "f31" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 18, mods, effective_et, None))
            }
            "f32" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 19, mods, effective_et, None))
            }
            "f33" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 20, mods, effective_et, None))
            }
            "f34" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 21, mods, effective_et, None))
            }
            "f35" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 22, mods, effective_et, None))
            }

            _ => {}
        }

        // C) Regular printable characters in Kitty mode.
        let key = keystroke.key.as_str();
        if let Some(ch) = key.chars().next() {
            if key.len() == ch.len_utf8() {
                // Kitty spec (disambiguate / level 1): Shift+printable is unambiguous.
                // send the shifted character via legacy encoding. CSI-u only when
                // non-shift modifiers need disambiguation, or all-keys mode is active.
                let need_csi_u = if kitty_all_keys { true } else { mods & !1 != 0 };

                if need_csi_u {
                    // ASCII letters use lowercase base codepoint per Kitty spec.
                    let codepoint = if ch.is_ascii() {
                        ch.to_ascii_lowercase() as u32
                    } else {
                        ch as u32
                    };
                    return Some(encode_csi_u_full(
                        codepoint,
                        mods,
                        effective_et,
                        effective_text,
                    ));
                }
            }
        }

        // Fall through to legacy encoding for unhandled cases
    }

    // -----------------------------------------------------------------------
    // Legacy encoding. No event type annotations possible.
    // Release of non-escape-encoded keys produces no output.
    // -----------------------------------------------------------------------
    if matches!(effective_et, Some(KeyEventType::Release)) {
        return None;
    }

    let legacy_mods = kitty_modifier_mask(&keystroke.modifiers);

    // macOS Terminal-style word motion: Option+Left/Right sends Meta-b / Meta-f
    // for shell line editing instead of xterm modified-arrow sequences.
    if cfg!(target_os = "macos")
        && keystroke.modifiers.alt
        && !keystroke.modifiers.control
        && !keystroke.modifiers.shift
        && !keystroke.modifiers.platform
    {
        match keystroke.key.as_str() {
            "left" => return Some(b"\x1bb".to_vec()),
            "right" => return Some(b"\x1bf".to_vec()),
            _ => {}
        }
    }

    // Handle special keys first
    match keystroke.key.as_str() {
        "space" => {
            if keystroke.modifiers.control {
                return Some(b"\x00".to_vec());
            }
            return Some(b" ".to_vec());
        }
        "enter" => return Some(b"\r".to_vec()),
        "escape" => return Some(b"\x1b".to_vec()),
        "backspace" => return Some(b"\x7f".to_vec()),
        "tab" => {
            if keystroke.modifiers.shift {
                return Some(b"\x1b[Z".to_vec());
            }
            return Some(b"\t".to_vec());
        }

        // Arrow keys
        "up" if legacy_mods > 0 => return Some(encode_csi_modified_letter('A', legacy_mods)),
        "down" if legacy_mods > 0 => return Some(encode_csi_modified_letter('B', legacy_mods)),
        "right" if legacy_mods > 0 => return Some(encode_csi_modified_letter('C', legacy_mods)),
        "left" if legacy_mods > 0 => return Some(encode_csi_modified_letter('D', legacy_mods)),
        "up" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOA".to_vec());
            }
            return Some(b"\x1b[A".to_vec());
        }
        "down" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOB".to_vec());
            }
            return Some(b"\x1b[B".to_vec());
        }
        "right" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOC".to_vec());
            }
            return Some(b"\x1b[C".to_vec());
        }
        "left" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOD".to_vec());
            }
            return Some(b"\x1b[D".to_vec());
        }

        // Navigation keys
        "home" if legacy_mods > 0 => return Some(encode_csi_modified_letter('H', legacy_mods)),
        "end" if legacy_mods > 0 => return Some(encode_csi_modified_letter('F', legacy_mods)),
        "home" => return Some(b"\x1b[H".to_vec()),
        "end" => return Some(b"\x1b[F".to_vec()),
        "pageup" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(5, legacy_mods)),
        "pagedown" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(6, legacy_mods)),
        "pageup" => return Some(b"\x1b[5~".to_vec()),
        "pagedown" => return Some(b"\x1b[6~".to_vec()),
        "insert" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(2, legacy_mods)),
        "delete" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(3, legacy_mods)),
        "insert" => return Some(b"\x1b[2~".to_vec()),
        "delete" => return Some(b"\x1b[3~".to_vec()),

        // Function keys
        "f1" if legacy_mods > 0 => return Some(encode_csi_modified_letter('P', legacy_mods)),
        "f2" if legacy_mods > 0 => return Some(encode_csi_modified_letter('Q', legacy_mods)),
        "f3" if legacy_mods > 0 => return Some(encode_csi_modified_letter('R', legacy_mods)),
        "f4" if legacy_mods > 0 => return Some(encode_csi_modified_letter('S', legacy_mods)),
        "f1" => return Some(b"\x1bOP".to_vec()),
        "f2" => return Some(b"\x1bOQ".to_vec()),
        "f3" => return Some(b"\x1bOR".to_vec()),
        "f4" => return Some(b"\x1bOS".to_vec()),
        "f5" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(15, legacy_mods)),
        "f6" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(17, legacy_mods)),
        "f7" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(18, legacy_mods)),
        "f8" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(19, legacy_mods)),
        "f9" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(20, legacy_mods)),
        "f10" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(21, legacy_mods)),
        "f11" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(23, legacy_mods)),
        "f12" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(24, legacy_mods)),
        "f5" => return Some(b"\x1b[15~".to_vec()),
        "f6" => return Some(b"\x1b[17~".to_vec()),
        "f7" => return Some(b"\x1b[18~".to_vec()),
        "f8" => return Some(b"\x1b[19~".to_vec()),
        "f9" => return Some(b"\x1b[20~".to_vec()),
        "f10" => return Some(b"\x1b[21~".to_vec()),
        "f11" => return Some(b"\x1b[23~".to_vec()),
        "f12" => return Some(b"\x1b[24~".to_vec()),
        "f13" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(25, legacy_mods)),
        "f14" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(26, legacy_mods)),
        "f15" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(28, legacy_mods)),
        "f16" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(29, legacy_mods)),
        "f17" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(31, legacy_mods)),
        "f18" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(32, legacy_mods)),
        "f19" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(33, legacy_mods)),
        "f20" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(34, legacy_mods)),
        "f13" => return Some(b"\x1b[25~".to_vec()),
        "f14" => return Some(b"\x1b[26~".to_vec()),
        "f15" => return Some(b"\x1b[28~".to_vec()),
        "f16" => return Some(b"\x1b[29~".to_vec()),
        "f17" => return Some(b"\x1b[31~".to_vec()),
        "f18" => return Some(b"\x1b[32~".to_vec()),
        "f19" => return Some(b"\x1b[33~".to_vec()),
        "f20" => return Some(b"\x1b[34~".to_vec()),

        _ => {}
    }

    // Ctrl+key combinations
    if keystroke.modifiers.control {
        let key = keystroke.key.as_str();
        if key.len() == 1 {
            let ch = key.chars().next().unwrap();
            if ch.is_ascii_alphabetic() {
                let upper = ch.to_ascii_uppercase();
                let ctrl_char = (upper as u8) - b'@';
                return Some(vec![ctrl_char]);
            }
            match ch {
                '[' => return Some(b"\x1b".to_vec()),
                '\\' => return Some(b"\x1c".to_vec()),
                ']' => return Some(b"\x1d".to_vec()),
                '^' => return Some(b"\x1e".to_vec()),
                '_' => return Some(b"\x1f".to_vec()),
                '?' => return Some(b"\x7f".to_vec()),
                _ => {}
            }
        }
    }

    // Alt+key combinations
    if keystroke.modifiers.alt {
        let key = keystroke.key.as_str();
        if key.len() == 1 {
            let ch = if let Some(kc) = &keystroke.key_char {
                kc.as_bytes().first().copied()
            } else {
                let c = key.chars().next().unwrap();
                if keystroke.modifiers.shift && c.is_ascii_alphabetic() {
                    Some(c.to_ascii_uppercase() as u8)
                } else {
                    Some(c as u8)
                }
            };
            if let Some(b) = ch {
                if b.is_ascii() {
                    return Some(vec![b'\x1b', b]);
                }
            }
        }
    }

    // Regular printable characters
    if let Some(key_char) = &keystroke.key_char {
        if !keystroke.modifiers.control && !keystroke.modifiers.alt {
            return Some(key_char.as_bytes().to_vec());
        }
    }

    // Fallback to key for single characters
    let key = keystroke.key.as_str();
    if key.len() == 1 {
        let ch = key.chars().next().unwrap();
        if ch.is_ascii() && !keystroke.modifiers.control {
            let ch = if keystroke.modifiers.shift {
                ch.to_ascii_uppercase()
            } else {
                ch
            };
            return Some(vec![ch as u8]);
        }
        if !keystroke.modifiers.control && !keystroke.modifiers.alt {
            return Some(key.as_bytes().to_vec());
        }
    }

    None
}

/// Convert a GPUI keystroke to terminal escape sequence bytes (Press events only).
///
/// Convenience wrapper around [`key_input_to_bytes`] for callers that don't
/// need event type or associated text tracking.
///
/// # Examples
///
/// ```
/// use gpui::Keystroke;
/// use alacritty_terminal::term::TermMode;
/// use orcashell_terminal_view::input::keystroke_to_bytes;
///
/// let keystroke = Keystroke::parse("enter").unwrap();
/// let bytes = keystroke_to_bytes(&keystroke, TermMode::empty());
/// assert_eq!(bytes, Some(b"\r".to_vec()));
/// ```
pub fn keystroke_to_bytes(keystroke: &Keystroke, mode: TermMode) -> Option<Vec<u8>> {
    key_input_to_bytes(
        &KeyInput {
            keystroke,
            event_type: KeyEventType::Press,
            associated_text: None,
        },
        mode,
    )
}

/// Wrap paste data in bracketed paste escape sequences when the terminal
/// has bracketed paste mode enabled. If the mode is not set, returns the
/// data unchanged.
///
/// Bracketed paste prevents the terminal from interpreting pasted text as
/// keyboard commands (e.g., a pasted newline won't execute a command).
pub fn wrap_bracketed_paste(data: &[u8], mode: TermMode) -> Vec<u8> {
    if mode.contains(TermMode::BRACKETED_PASTE) {
        let mut out = Vec::with_capacity(data.len() + 12);
        out.extend_from_slice(b"\x1b[200~");
        out.extend_from_slice(data);
        out.extend_from_slice(b"\x1b[201~");
        out
    } else {
        data.to_vec()
    }
}

#[cfg(test)]
mod tests;
