//! Keyboard input handling for the terminal emulator.
//!
//! This module provides [`keystroke_to_bytes`], which converts GPUI keyboard
//! events into terminal escape sequences that can be written to the PTY.
//!
//! # Key Mappings
//!
//! ## Special Keys
//!
//! | Key | Sequence | Notes |
//! |-----|----------|-------|
//! | Enter | `\r` (0x0D) | Carriage return |
//! | Escape | `\x1b` (0x1B) | ESC |
//! | Backspace | `\x7f` (0x7F) | DEL |
//! | Tab | `\t` (0x09) | Horizontal tab |
//! | Shift+Tab | `\x1b[Z` | Backtab |
//! | Space | ` ` (0x20) | Space |
//! | Ctrl+Space | `\x00` | NUL |
//!
//! ## Arrow Keys
//!
//! Arrow key sequences depend on application cursor mode:
//!
//! | Key | Normal Mode | App Cursor Mode |
//! |-----|-------------|-----------------|
//! | Up | `\x1b[A` | `\x1bOA` |
//! | Down | `\x1b[B` | `\x1bOB` |
//! | Right | `\x1b[C` | `\x1bOC` |
//! | Left | `\x1b[D` | `\x1bOD` |
//!
//! ## Navigation Keys
//!
//! | Key | Sequence |
//! |-----|----------|
//! | Home | `\x1b[H` |
//! | End | `\x1b[F` |
//! | PageUp | `\x1b[5~` |
//! | PageDown | `\x1b[6~` |
//! | Insert | `\x1b[2~` |
//! | Delete | `\x1b[3~` |
//!
//! ## Function Keys
//!
//! | Key | Sequence |
//! |-----|----------|
//! | F1-F4 | `\x1bOP` - `\x1bOS` |
//! | F5-F12 | `\x1b[15~` - `\x1b[24~` |
//!
//! ## Control Combinations
//!
//! Ctrl+A through Ctrl+Z map to ASCII control characters 0x01-0x1A:
//!
//! | Combination | Byte |
//! |-------------|------|
//! | Ctrl+A | 0x01 |
//! | Ctrl+C | 0x03 (interrupt) |
//! | Ctrl+D | 0x04 (EOF) |
//! | Ctrl+Z | 0x1A (suspend) |
//!
//! ## Alt Combinations
//!
//! Alt+key sends ESC followed by the key: `\x1b` + key
//!
//! # Terminal Mode Effects
//!
//! The [`TermMode`] flags affect key sequences:
//!
//! - **APP_CURSOR**: Changes arrow key sequences from CSI to SS3 format
//!
//! # Example
//!
//! ```
//! use gpui::Keystroke;
//! use alacritty_terminal::term::TermMode;
//! use orcashell_terminal_view::input::keystroke_to_bytes;
//!
//! // Enter key
//! let keystroke = Keystroke::parse("enter").unwrap();
//! assert_eq!(keystroke_to_bytes(&keystroke, TermMode::empty()), Some(b"\r".to_vec()));
//!
//! // Ctrl+C (interrupt)
//! let keystroke = Keystroke::parse("ctrl-c").unwrap();
//! assert_eq!(keystroke_to_bytes(&keystroke, TermMode::empty()), Some(vec![0x03]));
//! ```

use std::io::Write;

use alacritty_terminal::term::TermMode;
use gpui::{Keystroke, Modifiers};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// Kitty keyboard protocol event types (REPORT_EVENT_TYPES).
///
/// When `TermMode::REPORT_EVENT_TYPES` is active, the event type is appended
/// to the modifier parameter with a `:` separator in escape-encoded sequences.
/// Press (1) is the default and is always omitted on the wire.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KeyEventType {
    Press = 1,
    Repeat = 2,
    Release = 3,
}

/// Input event context for keyboard encoding.
///
/// Wraps a GPUI `Keystroke` with additional metadata needed for extended
/// Kitty keyboard protocol features (event types, associated text).
#[derive(Clone, Debug)]
pub struct KeyInput<'a> {
    pub keystroke: &'a Keystroke,
    pub event_type: KeyEventType,
    /// The text actually generated by this key event (from GPUI's `key_char`).
    /// Used for `REPORT_ASSOCIATED_TEXT` (Kitty level 5).
    pub associated_text: Option<&'a str>,
}

// ---------------------------------------------------------------------------
// Kitty modifier-key codepoints
// ---------------------------------------------------------------------------

/// Left Shift (GPUI doesn't distinguish left/right).
pub const KITTY_LEFT_SHIFT: u32 = 57441;
/// Left Control.
pub const KITTY_LEFT_CONTROL: u32 = 57442;
/// Left Alt / Option.
pub const KITTY_LEFT_ALT: u32 = 57443;
/// Left Super / Cmd.
pub const KITTY_LEFT_SUPER: u32 = 57444;
/// Caps Lock.
pub const KITTY_CAPS_LOCK: u32 = 57358;

// ---------------------------------------------------------------------------
// Modifier encoding
// ---------------------------------------------------------------------------

/// Compute the Kitty keyboard protocol modifier bitmask from GPUI modifiers.
///
/// Kitty spec bitmask: shift=1, alt=2, ctrl=4, super=8.
/// Returns 0 if no modifiers are active. The wire format sends `mask + 1`,
/// but this function returns the raw mask.
pub fn kitty_modifier_mask(modifiers: &Modifiers) -> u8 {
    let mut mask = 0u8;
    if modifiers.shift {
        mask |= 1;
    }
    if modifiers.alt {
        mask |= 2;
    }
    if modifiers.control {
        mask |= 4;
    }
    if modifiers.platform {
        mask |= 8;
    }
    mask
}

// ---------------------------------------------------------------------------
// CSI encoding helpers
// ---------------------------------------------------------------------------

/// Write the modifier+event_type sub-parameter: `{mods+1}` or `{mods+1}:{event_type}`.
///
/// Kitty spec rules:
/// - Press (1) is the default and is always omitted.
/// - If mods==0 and event_type==Press, the whole modifier param can be omitted
///   (caller decides whether to emit the `;`).
/// - If mods==0 but event_type is Repeat/Release, we must emit `1:{type}`
///   because the modifier field hosts the event-type sub-parameter.
fn write_mods_and_event(buf: &mut Vec<u8>, mods: u8, event_type: Option<KeyEventType>) {
    write!(buf, "{}", (mods as u16) + 1).unwrap();
    if let Some(et) = event_type {
        if !matches!(et, KeyEventType::Press) {
            write!(buf, ":{}", et as u8).unwrap();
        }
    }
}

/// Returns true if the modifier+event_type portion is non-trivial (needs emitting).
fn has_mod_or_event(mods: u8, event_type: Option<KeyEventType>) -> bool {
    mods > 0
        || matches!(
            event_type,
            Some(KeyEventType::Repeat) | Some(KeyEventType::Release)
        )
}

/// Encode associated text as colon-separated Unicode codepoints.
fn write_associated_text(buf: &mut Vec<u8>, text: &str) {
    for (i, ch) in text.chars().enumerate() {
        if i > 0 {
            buf.push(b':');
        }
        write!(buf, "{}", ch as u32).unwrap();
    }
}

/// Full Kitty CSI-u encoding: `\x1b[{codepoint};{mods+1}:{event_type};{text_codepoints}u`
///
/// Omits trailing parameters when they are at their default values.
/// Release events never include associated text.
fn encode_csi_u_full(
    codepoint: u32,
    mods: u8,
    event_type: Option<KeyEventType>,
    associated_text: Option<&str>,
) -> Vec<u8> {
    // Release events never include associated text per spec.
    let text = if matches!(event_type, Some(KeyEventType::Release)) {
        None
    } else {
        associated_text.filter(|t| !t.is_empty())
    };

    let has_mods = has_mod_or_event(mods, event_type);
    let has_text = text.is_some();

    let mut buf = Vec::with_capacity(24);
    buf.extend_from_slice(b"\x1b[");
    write!(buf, "{}", codepoint).unwrap();

    if has_mods || has_text {
        buf.push(b';');
        // Only write the modifier+event_type sub-param if there's something to report.
        // When mods=0 and event_type=Press but text follows, leave the field empty
        // so the encoding is `CSI codepoint;;text u`.
        if has_mods {
            write_mods_and_event(&mut buf, mods, event_type);
        }
    }
    if has_text {
        buf.push(b';');
        write_associated_text(&mut buf, text.unwrap());
    }
    buf.push(b'u');
    buf
}

/// Encode a letter-terminated functional key: `\x1b[1;{mods+1}:{event_type}{suffix}`
///
/// Used for arrows (A/B/C/D), home (H), end (F), F1-F4 (P/Q/R/S).
fn encode_csi_modified_letter_full(
    suffix: char,
    mods: u8,
    event_type: Option<KeyEventType>,
) -> Vec<u8> {
    let mut buf = Vec::with_capacity(16);
    buf.extend_from_slice(b"\x1b[1;");
    write_mods_and_event(&mut buf, mods, event_type);
    buf.push(suffix as u8);
    buf
}

/// Simple letter-terminated encoding (backward-compat wrapper).
fn encode_csi_modified_letter(suffix: char, mods: u8) -> Vec<u8> {
    encode_csi_modified_letter_full(suffix, mods, None)
}

/// Encode a tilde-terminated functional key: `\x1b[{num};{mods+1}:{event_type}~`
///
/// Used for pageup/down (5/6), insert/delete (2/3), F5-F12.
fn encode_csi_modified_tilde_full(num: u32, mods: u8, event_type: Option<KeyEventType>) -> Vec<u8> {
    let mut buf = Vec::with_capacity(16);
    write!(buf, "\x1b[{};", num).unwrap();
    write_mods_and_event(&mut buf, mods, event_type);
    buf.push(b'~');
    buf
}

/// Simple tilde-terminated encoding (backward-compat wrapper).
fn encode_csi_modified_tilde(num: u32, mods: u8) -> Vec<u8> {
    encode_csi_modified_tilde_full(num, mods, None)
}

/// Encode a modifier-only key press/release for the Kitty protocol.
///
/// Used by `terminal_view.rs` when handling `ModifiersChangedEvent` to report
/// modifier key events (shift, ctrl, alt, super) to applications that request
/// `REPORT_ALL_KEYS_AS_ESC` + `REPORT_EVENT_TYPES`.
pub fn modifier_key_to_bytes(
    codepoint: u32,
    mods: u8,
    event_type: KeyEventType,
    mode: TermMode,
) -> Option<Vec<u8>> {
    if !mode.contains(TermMode::REPORT_EVENT_TYPES) {
        return None;
    }
    let et = if matches!(event_type, KeyEventType::Press) {
        None
    } else {
        Some(event_type)
    };
    Some(encode_csi_u_full(codepoint, mods, et, None))
}

/// Convert a [`KeyInput`] to terminal escape sequence bytes.
///
/// This is the primary encoding function supporting the full Kitty keyboard
/// protocol including `REPORT_EVENT_TYPES` and `REPORT_ASSOCIATED_TEXT`.
///
/// **Critical semantics:** `REPORT_EVENT_TYPES` does NOT promote text keys to
/// CSI-u. Event type annotations (`:2` repeat, `:3` release) can only be
/// attached to keys that are already escape-encoded by another mode flag.
/// Text-producing keys stay as plain UTF-8 unless `REPORT_ALL_KEYS_AS_ESC`
/// is also active (per Kitty spec / VTE `ansi.rs:767-769`).
pub fn key_input_to_bytes(input: &KeyInput, mode: TermMode) -> Option<Vec<u8>> {
    let keystroke = input.keystroke;
    let report_event_types = mode.contains(TermMode::REPORT_EVENT_TYPES);
    let report_associated_text = mode.contains(TermMode::REPORT_ASSOCIATED_TEXT);

    // Pre-process event type: None means Press (default, omitted on wire).
    // Without REPORT_EVENT_TYPES, Release produces no output and Repeat is
    // treated as Press.
    let effective_et = if report_event_types {
        match input.event_type {
            KeyEventType::Press => None,
            other => Some(other),
        }
    } else {
        if matches!(input.event_type, KeyEventType::Release) {
            return None;
        }
        None
    };

    // Pre-process associated text.
    let effective_text = if report_associated_text {
        input.associated_text.filter(|t| !t.is_empty())
    } else {
        None
    };

    // -----------------------------------------------------------------------
    // Kitty keyboard protocol encoding
    // -----------------------------------------------------------------------
    let kitty_disambiguate = mode.contains(TermMode::DISAMBIGUATE_ESC_CODES);
    let kitty_all_keys = mode.contains(TermMode::REPORT_ALL_KEYS_AS_ESC);

    if kitty_disambiguate || kitty_all_keys {
        let mods = kitty_modifier_mask(&keystroke.modifiers);
        let has_mods = mods != 0;
        let use_csi_u = kitty_all_keys || has_mods;

        // Functional keys get event annotations even without keyboard modifiers,
        // because they are naturally escape-encoded (CSI sequences).
        let functional_annotate = has_mods || effective_et.is_some();

        // A) Special keys with Kitty codepoints (CSI-u format).
        // Associated text is omitted for enter/escape/backspace/tab. Their codepoint
        // already encodes the text, and Kitty itself omits it for these keys. Space
        // passes effective_text since it produces a printable character.
        match keystroke.key.as_str() {
            "enter" if use_csi_u => return Some(encode_csi_u_full(13, mods, effective_et, None)),
            "escape" if use_csi_u => return Some(encode_csi_u_full(27, mods, effective_et, None)),
            "backspace" if use_csi_u => {
                return Some(encode_csi_u_full(127, mods, effective_et, None))
            }
            "tab" if use_csi_u => return Some(encode_csi_u_full(9, mods, effective_et, None)),
            "space" if use_csi_u => {
                return Some(encode_csi_u_full(32, mods, effective_et, effective_text))
            }

            // B) Functional keys - CSI modified form with event type annotation.
            // Guard is expanded: has_mods OR need event annotation (repeat/release).
            "up" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('A', mods, effective_et))
            }
            "down" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('B', mods, effective_et))
            }
            "right" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('C', mods, effective_et))
            }
            "left" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('D', mods, effective_et))
            }

            "home" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('H', mods, effective_et))
            }
            "end" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('F', mods, effective_et))
            }
            "insert" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(2, mods, effective_et))
            }
            "delete" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(3, mods, effective_et))
            }
            "pageup" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(5, mods, effective_et))
            }
            "pagedown" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(6, mods, effective_et))
            }

            "f1" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('P', mods, effective_et))
            }
            "f2" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('Q', mods, effective_et))
            }
            "f3" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('R', mods, effective_et))
            }
            "f4" if functional_annotate => {
                return Some(encode_csi_modified_letter_full('S', mods, effective_et))
            }
            "f5" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(15, mods, effective_et))
            }
            "f6" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(17, mods, effective_et))
            }
            "f7" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(18, mods, effective_et))
            }
            "f8" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(19, mods, effective_et))
            }
            "f9" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(20, mods, effective_et))
            }
            "f10" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(21, mods, effective_et))
            }
            "f11" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(23, mods, effective_et))
            }
            "f12" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(24, mods, effective_et))
            }
            "f13" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(25, mods, effective_et))
            }
            "f14" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(26, mods, effective_et))
            }
            "f15" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(28, mods, effective_et))
            }
            "f16" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(29, mods, effective_et))
            }
            "f17" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(31, mods, effective_et))
            }
            "f18" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(32, mods, effective_et))
            }
            "f19" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(33, mods, effective_et))
            }
            "f20" if functional_annotate => {
                return Some(encode_csi_modified_tilde_full(34, mods, effective_et))
            }
            // F21-F35: use Kitty codepoints in CSI-u format (no standard legacy tilde codes)
            "f21" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 8, mods, effective_et, None))
            }
            "f22" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 9, mods, effective_et, None))
            }
            "f23" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 10, mods, effective_et, None))
            }
            "f24" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 11, mods, effective_et, None))
            }
            "f25" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 12, mods, effective_et, None))
            }
            "f26" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 13, mods, effective_et, None))
            }
            "f27" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 14, mods, effective_et, None))
            }
            "f28" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 15, mods, effective_et, None))
            }
            "f29" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 16, mods, effective_et, None))
            }
            "f30" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 17, mods, effective_et, None))
            }
            "f31" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 18, mods, effective_et, None))
            }
            "f32" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 19, mods, effective_et, None))
            }
            "f33" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 20, mods, effective_et, None))
            }
            "f34" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 21, mods, effective_et, None))
            }
            "f35" if functional_annotate => {
                return Some(encode_csi_u_full(57376 + 22, mods, effective_et, None))
            }

            _ => {}
        }

        // C) Regular printable characters in Kitty mode.
        let key = keystroke.key.as_str();
        if let Some(ch) = key.chars().next() {
            if key.len() == ch.len_utf8() {
                // Kitty spec (disambiguate / level 1): Shift+printable is unambiguous.
                // send the shifted character via legacy encoding. CSI-u only when
                // non-shift modifiers need disambiguation, or all-keys mode is active.
                let need_csi_u = if kitty_all_keys { true } else { mods & !1 != 0 };

                if need_csi_u {
                    // ASCII letters use lowercase base codepoint per Kitty spec.
                    let codepoint = if ch.is_ascii() {
                        ch.to_ascii_lowercase() as u32
                    } else {
                        ch as u32
                    };
                    return Some(encode_csi_u_full(
                        codepoint,
                        mods,
                        effective_et,
                        effective_text,
                    ));
                }
            }
        }

        // Fall through to legacy encoding for unhandled cases
    }

    // -----------------------------------------------------------------------
    // Legacy encoding. No event type annotations possible.
    // Release of non-escape-encoded keys produces no output.
    // -----------------------------------------------------------------------
    if matches!(effective_et, Some(KeyEventType::Release)) {
        return None;
    }

    let legacy_mods = kitty_modifier_mask(&keystroke.modifiers);

    // Handle special keys first
    match keystroke.key.as_str() {
        "space" => {
            if keystroke.modifiers.control {
                return Some(b"\x00".to_vec());
            }
            return Some(b" ".to_vec());
        }
        "enter" => return Some(b"\r".to_vec()),
        "escape" => return Some(b"\x1b".to_vec()),
        "backspace" => return Some(b"\x7f".to_vec()),
        "tab" => {
            if keystroke.modifiers.shift {
                return Some(b"\x1b[Z".to_vec());
            }
            return Some(b"\t".to_vec());
        }

        // Arrow keys
        "up" if legacy_mods > 0 => return Some(encode_csi_modified_letter('A', legacy_mods)),
        "down" if legacy_mods > 0 => return Some(encode_csi_modified_letter('B', legacy_mods)),
        "right" if legacy_mods > 0 => return Some(encode_csi_modified_letter('C', legacy_mods)),
        "left" if legacy_mods > 0 => return Some(encode_csi_modified_letter('D', legacy_mods)),
        "up" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOA".to_vec());
            }
            return Some(b"\x1b[A".to_vec());
        }
        "down" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOB".to_vec());
            }
            return Some(b"\x1b[B".to_vec());
        }
        "right" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOC".to_vec());
            }
            return Some(b"\x1b[C".to_vec());
        }
        "left" => {
            if mode.contains(TermMode::APP_CURSOR) {
                return Some(b"\x1bOD".to_vec());
            }
            return Some(b"\x1b[D".to_vec());
        }

        // Navigation keys
        "home" if legacy_mods > 0 => return Some(encode_csi_modified_letter('H', legacy_mods)),
        "end" if legacy_mods > 0 => return Some(encode_csi_modified_letter('F', legacy_mods)),
        "home" => return Some(b"\x1b[H".to_vec()),
        "end" => return Some(b"\x1b[F".to_vec()),
        "pageup" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(5, legacy_mods)),
        "pagedown" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(6, legacy_mods)),
        "pageup" => return Some(b"\x1b[5~".to_vec()),
        "pagedown" => return Some(b"\x1b[6~".to_vec()),
        "insert" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(2, legacy_mods)),
        "delete" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(3, legacy_mods)),
        "insert" => return Some(b"\x1b[2~".to_vec()),
        "delete" => return Some(b"\x1b[3~".to_vec()),

        // Function keys
        "f1" if legacy_mods > 0 => return Some(encode_csi_modified_letter('P', legacy_mods)),
        "f2" if legacy_mods > 0 => return Some(encode_csi_modified_letter('Q', legacy_mods)),
        "f3" if legacy_mods > 0 => return Some(encode_csi_modified_letter('R', legacy_mods)),
        "f4" if legacy_mods > 0 => return Some(encode_csi_modified_letter('S', legacy_mods)),
        "f1" => return Some(b"\x1bOP".to_vec()),
        "f2" => return Some(b"\x1bOQ".to_vec()),
        "f3" => return Some(b"\x1bOR".to_vec()),
        "f4" => return Some(b"\x1bOS".to_vec()),
        "f5" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(15, legacy_mods)),
        "f6" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(17, legacy_mods)),
        "f7" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(18, legacy_mods)),
        "f8" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(19, legacy_mods)),
        "f9" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(20, legacy_mods)),
        "f10" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(21, legacy_mods)),
        "f11" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(23, legacy_mods)),
        "f12" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(24, legacy_mods)),
        "f5" => return Some(b"\x1b[15~".to_vec()),
        "f6" => return Some(b"\x1b[17~".to_vec()),
        "f7" => return Some(b"\x1b[18~".to_vec()),
        "f8" => return Some(b"\x1b[19~".to_vec()),
        "f9" => return Some(b"\x1b[20~".to_vec()),
        "f10" => return Some(b"\x1b[21~".to_vec()),
        "f11" => return Some(b"\x1b[23~".to_vec()),
        "f12" => return Some(b"\x1b[24~".to_vec()),
        "f13" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(25, legacy_mods)),
        "f14" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(26, legacy_mods)),
        "f15" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(28, legacy_mods)),
        "f16" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(29, legacy_mods)),
        "f17" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(31, legacy_mods)),
        "f18" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(32, legacy_mods)),
        "f19" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(33, legacy_mods)),
        "f20" if legacy_mods > 0 => return Some(encode_csi_modified_tilde(34, legacy_mods)),
        "f13" => return Some(b"\x1b[25~".to_vec()),
        "f14" => return Some(b"\x1b[26~".to_vec()),
        "f15" => return Some(b"\x1b[28~".to_vec()),
        "f16" => return Some(b"\x1b[29~".to_vec()),
        "f17" => return Some(b"\x1b[31~".to_vec()),
        "f18" => return Some(b"\x1b[32~".to_vec()),
        "f19" => return Some(b"\x1b[33~".to_vec()),
        "f20" => return Some(b"\x1b[34~".to_vec()),

        _ => {}
    }

    // Ctrl+key combinations
    if keystroke.modifiers.control {
        let key = keystroke.key.as_str();
        if key.len() == 1 {
            let ch = key.chars().next().unwrap();
            if ch.is_ascii_alphabetic() {
                let upper = ch.to_ascii_uppercase();
                let ctrl_char = (upper as u8) - b'@';
                return Some(vec![ctrl_char]);
            }
            match ch {
                '[' => return Some(b"\x1b".to_vec()),
                '\\' => return Some(b"\x1c".to_vec()),
                ']' => return Some(b"\x1d".to_vec()),
                '^' => return Some(b"\x1e".to_vec()),
                '_' => return Some(b"\x1f".to_vec()),
                '?' => return Some(b"\x7f".to_vec()),
                _ => {}
            }
        }
    }

    // Alt+key combinations
    if keystroke.modifiers.alt {
        let key = keystroke.key.as_str();
        if key.len() == 1 {
            let ch = if let Some(kc) = &keystroke.key_char {
                kc.as_bytes().first().copied()
            } else {
                let c = key.chars().next().unwrap();
                if keystroke.modifiers.shift && c.is_ascii_alphabetic() {
                    Some(c.to_ascii_uppercase() as u8)
                } else {
                    Some(c as u8)
                }
            };
            if let Some(b) = ch {
                if b.is_ascii() {
                    return Some(vec![b'\x1b', b]);
                }
            }
        }
    }

    // Regular printable characters
    if let Some(key_char) = &keystroke.key_char {
        if !keystroke.modifiers.control && !keystroke.modifiers.alt {
            return Some(key_char.as_bytes().to_vec());
        }
    }

    // Fallback to key for single characters
    let key = keystroke.key.as_str();
    if key.len() == 1 {
        let ch = key.chars().next().unwrap();
        if ch.is_ascii() && !keystroke.modifiers.control {
            let ch = if keystroke.modifiers.shift {
                ch.to_ascii_uppercase()
            } else {
                ch
            };
            return Some(vec![ch as u8]);
        }
        if !keystroke.modifiers.control && !keystroke.modifiers.alt {
            return Some(key.as_bytes().to_vec());
        }
    }

    None
}

/// Convert a GPUI keystroke to terminal escape sequence bytes (Press events only).
///
/// Convenience wrapper around [`key_input_to_bytes`] for callers that don't
/// need event type or associated text tracking.
///
/// # Examples
///
/// ```
/// use gpui::Keystroke;
/// use alacritty_terminal::term::TermMode;
/// use orcashell_terminal_view::input::keystroke_to_bytes;
///
/// let keystroke = Keystroke::parse("enter").unwrap();
/// let bytes = keystroke_to_bytes(&keystroke, TermMode::empty());
/// assert_eq!(bytes, Some(b"\r".to_vec()));
/// ```
pub fn keystroke_to_bytes(keystroke: &Keystroke, mode: TermMode) -> Option<Vec<u8>> {
    key_input_to_bytes(
        &KeyInput {
            keystroke,
            event_type: KeyEventType::Press,
            associated_text: None,
        },
        mode,
    )
}

/// Wrap paste data in bracketed paste escape sequences when the terminal
/// has bracketed paste mode enabled. If the mode is not set, returns the
/// data unchanged.
///
/// Bracketed paste prevents the terminal from interpreting pasted text as
/// keyboard commands (e.g., a pasted newline won't execute a command).
pub fn wrap_bracketed_paste(data: &[u8], mode: TermMode) -> Vec<u8> {
    if mode.contains(TermMode::BRACKETED_PASTE) {
        let mut out = Vec::with_capacity(data.len() + 12);
        out.extend_from_slice(b"\x1b[200~");
        out.extend_from_slice(data);
        out.extend_from_slice(b"\x1b[201~");
        out
    } else {
        data.to_vec()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_enter_key() {
        let keystroke = Keystroke::parse("enter").unwrap();
        let bytes = keystroke_to_bytes(&keystroke, TermMode::empty());
        assert_eq!(bytes, Some(b"\r".to_vec()));
    }

    #[test]
    fn test_escape_key() {
        let keystroke = Keystroke::parse("escape").unwrap();
        let bytes = keystroke_to_bytes(&keystroke, TermMode::empty());
        assert_eq!(bytes, Some(b"\x1b".to_vec()));
    }

    #[test]
    fn test_backspace_key() {
        let keystroke = Keystroke::parse("backspace").unwrap();
        let bytes = keystroke_to_bytes(&keystroke, TermMode::empty());
        assert_eq!(bytes, Some(b"\x7f".to_vec()));
    }

    #[test]
    fn test_tab_key() {
        let keystroke = Keystroke::parse("tab").unwrap();
        let bytes = keystroke_to_bytes(&keystroke, TermMode::empty());
        assert_eq!(bytes, Some(b"\t".to_vec()));
    }

    #[test]
    fn test_shift_tab() {
        let keystroke = Keystroke::parse("shift-tab").unwrap();
        let bytes = keystroke_to_bytes(&keystroke, TermMode::empty());
        assert_eq!(bytes, Some(b"\x1b[Z".to_vec()));
    }

    #[test]
    fn test_arrow_keys_normal_mode() {
        let mode = TermMode::empty();

        let up = Keystroke::parse("up").unwrap();
        assert_eq!(keystroke_to_bytes(&up, mode), Some(b"\x1b[A".to_vec()));

        let down = Keystroke::parse("down").unwrap();
        assert_eq!(keystroke_to_bytes(&down, mode), Some(b"\x1b[B".to_vec()));

        let right = Keystroke::parse("right").unwrap();
        assert_eq!(keystroke_to_bytes(&right, mode), Some(b"\x1b[C".to_vec()));

        let left = Keystroke::parse("left").unwrap();
        assert_eq!(keystroke_to_bytes(&left, mode), Some(b"\x1b[D".to_vec()));
    }

    #[test]
    fn test_arrow_keys_app_cursor_mode() {
        let mode = TermMode::APP_CURSOR;

        let up = Keystroke::parse("up").unwrap();
        assert_eq!(keystroke_to_bytes(&up, mode), Some(b"\x1bOA".to_vec()));

        let down = Keystroke::parse("down").unwrap();
        assert_eq!(keystroke_to_bytes(&down, mode), Some(b"\x1bOB".to_vec()));

        let right = Keystroke::parse("right").unwrap();
        assert_eq!(keystroke_to_bytes(&right, mode), Some(b"\x1bOC".to_vec()));

        let left = Keystroke::parse("left").unwrap();
        assert_eq!(keystroke_to_bytes(&left, mode), Some(b"\x1bOD".to_vec()));
    }

    #[test]
    fn test_navigation_keys() {
        let mode = TermMode::empty();

        let home = Keystroke::parse("home").unwrap();
        assert_eq!(keystroke_to_bytes(&home, mode), Some(b"\x1b[H".to_vec()));

        let end = Keystroke::parse("end").unwrap();
        assert_eq!(keystroke_to_bytes(&end, mode), Some(b"\x1b[F".to_vec()));

        let pageup = Keystroke::parse("pageup").unwrap();
        assert_eq!(keystroke_to_bytes(&pageup, mode), Some(b"\x1b[5~".to_vec()));

        let pagedown = Keystroke::parse("pagedown").unwrap();
        assert_eq!(
            keystroke_to_bytes(&pagedown, mode),
            Some(b"\x1b[6~".to_vec())
        );

        let insert = Keystroke::parse("insert").unwrap();
        assert_eq!(keystroke_to_bytes(&insert, mode), Some(b"\x1b[2~".to_vec()));

        let delete = Keystroke::parse("delete").unwrap();
        assert_eq!(keystroke_to_bytes(&delete, mode), Some(b"\x1b[3~".to_vec()));
    }

    #[test]
    fn test_function_keys() {
        let mode = TermMode::empty();

        let f1 = Keystroke::parse("f1").unwrap();
        assert_eq!(keystroke_to_bytes(&f1, mode), Some(b"\x1bOP".to_vec()));

        let f2 = Keystroke::parse("f2").unwrap();
        assert_eq!(keystroke_to_bytes(&f2, mode), Some(b"\x1bOQ".to_vec()));

        let f5 = Keystroke::parse("f5").unwrap();
        assert_eq!(keystroke_to_bytes(&f5, mode), Some(b"\x1b[15~".to_vec()));

        let f12 = Keystroke::parse("f12").unwrap();
        assert_eq!(keystroke_to_bytes(&f12, mode), Some(b"\x1b[24~".to_vec()));
    }

    #[test]
    fn test_legacy_modified_arrows() {
        let mode = TermMode::empty();

        // Shift+Up → xterm modified form \x1b[1;2A
        let shift_up = Keystroke::parse("shift-up").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_up, mode),
            Some(b"\x1b[1;2A".to_vec())
        );

        // Ctrl+Right → \x1b[1;5C
        let ctrl_right = Keystroke::parse("ctrl-right").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_right, mode),
            Some(b"\x1b[1;5C".to_vec())
        );

        // Alt+Left → \x1b[1;3D
        let alt_left = Keystroke::parse("alt-left").unwrap();
        assert_eq!(
            keystroke_to_bytes(&alt_left, mode),
            Some(b"\x1b[1;3D".to_vec())
        );

        // Unmodified arrows still work normally
        let up = Keystroke::parse("up").unwrap();
        assert_eq!(keystroke_to_bytes(&up, mode), Some(b"\x1b[A".to_vec()));

        // Unmodified + APP_CURSOR still works
        let app_mode = TermMode::APP_CURSOR;
        assert_eq!(keystroke_to_bytes(&up, app_mode), Some(b"\x1bOA".to_vec()));
    }

    #[test]
    fn test_legacy_modified_nav_and_fkeys() {
        let mode = TermMode::empty();

        // Shift+Home → \x1b[1;2H
        let shift_home = Keystroke::parse("shift-home").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_home, mode),
            Some(b"\x1b[1;2H".to_vec())
        );

        // Ctrl+Delete → \x1b[3;5~
        let ctrl_delete = Keystroke::parse("ctrl-delete").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_delete, mode),
            Some(b"\x1b[3;5~".to_vec())
        );

        // Shift+F5 → \x1b[15;2~
        let shift_f5 = Keystroke::parse("shift-f5").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_f5, mode),
            Some(b"\x1b[15;2~".to_vec())
        );

        // Shift+F1 → \x1b[1;2P
        let shift_f1 = Keystroke::parse("shift-f1").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_f1, mode),
            Some(b"\x1b[1;2P".to_vec())
        );
    }

    #[test]
    fn test_ctrl_combinations() {
        let mode = TermMode::empty();

        // Ctrl+A = 0x01
        let ctrl_a = Keystroke::parse("ctrl-a").unwrap();
        assert_eq!(keystroke_to_bytes(&ctrl_a, mode), Some(vec![0x01]));

        // Ctrl+C = 0x03
        let ctrl_c = Keystroke::parse("ctrl-c").unwrap();
        assert_eq!(keystroke_to_bytes(&ctrl_c, mode), Some(vec![0x03]));

        // Ctrl+Z = 0x1a
        let ctrl_z = Keystroke::parse("ctrl-z").unwrap();
        assert_eq!(keystroke_to_bytes(&ctrl_z, mode), Some(vec![0x1a]));

        // Ctrl+Space = 0x00
        let ctrl_space = Keystroke::parse("ctrl-space").unwrap();
        assert_eq!(keystroke_to_bytes(&ctrl_space, mode), Some(vec![0x00]));
    }

    #[test]
    fn test_alt_combinations() {
        let mode = TermMode::empty();

        // Alt+a sends ESC followed by 'a'
        let alt_a = Keystroke::parse("alt-a").unwrap();
        assert_eq!(keystroke_to_bytes(&alt_a, mode), Some(b"\x1ba".to_vec()));

        // Alt+x sends ESC followed by 'x'
        let alt_x = Keystroke::parse("alt-x").unwrap();
        assert_eq!(keystroke_to_bytes(&alt_x, mode), Some(b"\x1bx".to_vec()));

        // Alt+Shift+a sends ESC followed by 'A' (uppercase)
        let alt_shift_a = Keystroke::parse("alt-shift-a").unwrap();
        assert_eq!(
            keystroke_to_bytes(&alt_shift_a, mode),
            Some(b"\x1bA".to_vec())
        );
    }

    #[test]
    fn test_regular_characters() {
        let mode = TermMode::empty();

        let a = Keystroke::parse("a").unwrap();
        assert_eq!(keystroke_to_bytes(&a, mode), Some(b"a".to_vec()));

        let z = Keystroke::parse("z").unwrap();
        assert_eq!(keystroke_to_bytes(&z, mode), Some(b"z".to_vec()));

        let zero = Keystroke::parse("0").unwrap();
        assert_eq!(keystroke_to_bytes(&zero, mode), Some(b"0".to_vec()));
    }

    #[test]
    fn test_space_key() {
        let mode = TermMode::empty();

        let space = Keystroke::parse("space").unwrap();
        assert_eq!(keystroke_to_bytes(&space, mode), Some(b" ".to_vec()));
    }

    #[test]
    fn test_bracketed_paste_enabled() {
        let mode = TermMode::BRACKETED_PASTE;
        let result = wrap_bracketed_paste(b"hello\nworld", mode);
        assert_eq!(result, b"\x1b[200~hello\nworld\x1b[201~");
    }

    #[test]
    fn test_bracketed_paste_disabled() {
        let mode = TermMode::empty();
        let result = wrap_bracketed_paste(b"hello\nworld", mode);
        assert_eq!(result, b"hello\nworld");
    }

    #[test]
    fn test_bracketed_paste_empty_data() {
        let mode = TermMode::BRACKETED_PASTE;
        let result = wrap_bracketed_paste(b"", mode);
        assert_eq!(result, b"\x1b[200~\x1b[201~");
    }

    // ── Kitty keyboard protocol tests ──────────────────────────────────

    #[test]
    fn test_kitty_modifier_mask() {
        use gpui::Modifiers;

        let none = Modifiers::default();
        assert_eq!(kitty_modifier_mask(&none), 0);

        let shift = Modifiers {
            shift: true,
            ..Default::default()
        };
        assert_eq!(kitty_modifier_mask(&shift), 1);

        let alt = Modifiers {
            alt: true,
            ..Default::default()
        };
        assert_eq!(kitty_modifier_mask(&alt), 2);

        let ctrl = Modifiers {
            control: true,
            ..Default::default()
        };
        assert_eq!(kitty_modifier_mask(&ctrl), 4);

        let super_mod = Modifiers {
            platform: true,
            ..Default::default()
        };
        assert_eq!(kitty_modifier_mask(&super_mod), 8);

        let ctrl_shift = Modifiers {
            control: true,
            shift: true,
            ..Default::default()
        };
        assert_eq!(kitty_modifier_mask(&ctrl_shift), 5);

        let ctrl_alt_shift = Modifiers {
            control: true,
            alt: true,
            shift: true,
            ..Default::default()
        };
        assert_eq!(kitty_modifier_mask(&ctrl_alt_shift), 7);
    }

    #[test]
    fn test_kitty_special_keys_disambiguate() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES;

        // Unmodified special keys fall through to legacy in level 1
        let enter = Keystroke::parse("enter").unwrap();
        assert_eq!(keystroke_to_bytes(&enter, mode), Some(b"\r".to_vec()));

        let esc = Keystroke::parse("escape").unwrap();
        assert_eq!(keystroke_to_bytes(&esc, mode), Some(b"\x1b".to_vec()));

        let tab = Keystroke::parse("tab").unwrap();
        assert_eq!(keystroke_to_bytes(&tab, mode), Some(b"\t".to_vec()));

        let bs = Keystroke::parse("backspace").unwrap();
        assert_eq!(keystroke_to_bytes(&bs, mode), Some(b"\x7f".to_vec()));

        let space = Keystroke::parse("space").unwrap();
        assert_eq!(keystroke_to_bytes(&space, mode), Some(b" ".to_vec()));

        // Modified special keys use CSI-u
        let shift_enter = Keystroke::parse("shift-enter").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_enter, mode),
            Some(b"\x1b[13;2u".to_vec())
        );

        let ctrl_enter = Keystroke::parse("ctrl-enter").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_enter, mode),
            Some(b"\x1b[13;5u".to_vec())
        );

        let shift_tab = Keystroke::parse("shift-tab").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_tab, mode),
            Some(b"\x1b[9;2u".to_vec())
        );

        let ctrl_space = Keystroke::parse("ctrl-space").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_space, mode),
            Some(b"\x1b[32;5u".to_vec())
        );

        let shift_backspace = Keystroke::parse("shift-backspace").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_backspace, mode),
            Some(b"\x1b[127;2u".to_vec())
        );
    }

    #[test]
    fn test_kitty_special_keys_all_keys() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_ALL_KEYS_AS_ESC;

        // In level 4, even unmodified special keys use CSI-u
        let enter = Keystroke::parse("enter").unwrap();
        assert_eq!(keystroke_to_bytes(&enter, mode), Some(b"\x1b[13u".to_vec()));

        let tab = Keystroke::parse("tab").unwrap();
        assert_eq!(keystroke_to_bytes(&tab, mode), Some(b"\x1b[9u".to_vec()));

        let esc = Keystroke::parse("escape").unwrap();
        assert_eq!(keystroke_to_bytes(&esc, mode), Some(b"\x1b[27u".to_vec()));

        let space = Keystroke::parse("space").unwrap();
        assert_eq!(keystroke_to_bytes(&space, mode), Some(b"\x1b[32u".to_vec()));

        let bs = Keystroke::parse("backspace").unwrap();
        assert_eq!(keystroke_to_bytes(&bs, mode), Some(b"\x1b[127u".to_vec()));

        // Modified special keys in level 4
        let shift_enter = Keystroke::parse("shift-enter").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_enter, mode),
            Some(b"\x1b[13;2u".to_vec())
        );
    }

    #[test]
    fn test_kitty_arrows_with_modifiers() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES;

        let shift_up = Keystroke::parse("shift-up").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_up, mode),
            Some(b"\x1b[1;2A".to_vec())
        );

        let ctrl_down = Keystroke::parse("ctrl-down").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_down, mode),
            Some(b"\x1b[1;5B".to_vec())
        );

        let ctrl_right = Keystroke::parse("ctrl-right").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_right, mode),
            Some(b"\x1b[1;5C".to_vec())
        );

        let alt_left = Keystroke::parse("alt-left").unwrap();
        assert_eq!(
            keystroke_to_bytes(&alt_left, mode),
            Some(b"\x1b[1;3D".to_vec())
        );
    }

    #[test]
    fn test_kitty_arrows_unmodified_legacy() {
        // Unmodified arrows in Kitty mode fall through to legacy
        let mode = TermMode::DISAMBIGUATE_ESC_CODES;
        let up = Keystroke::parse("up").unwrap();
        assert_eq!(keystroke_to_bytes(&up, mode), Some(b"\x1b[A".to_vec()));

        // APP_CURSOR still applies for unmodified arrows
        let mode_app = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::APP_CURSOR;
        assert_eq!(keystroke_to_bytes(&up, mode_app), Some(b"\x1bOA".to_vec()));
    }

    #[test]
    fn test_kitty_nav_keys_with_modifiers() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES;

        let shift_home = Keystroke::parse("shift-home").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_home, mode),
            Some(b"\x1b[1;2H".to_vec())
        );

        let ctrl_end = Keystroke::parse("ctrl-end").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_end, mode),
            Some(b"\x1b[1;5F".to_vec())
        );

        let ctrl_pageup = Keystroke::parse("ctrl-pageup").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_pageup, mode),
            Some(b"\x1b[5;5~".to_vec())
        );

        let shift_pagedown = Keystroke::parse("shift-pagedown").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_pagedown, mode),
            Some(b"\x1b[6;2~".to_vec())
        );

        let ctrl_delete = Keystroke::parse("ctrl-delete").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_delete, mode),
            Some(b"\x1b[3;5~".to_vec())
        );

        let shift_insert = Keystroke::parse("shift-insert").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_insert, mode),
            Some(b"\x1b[2;2~".to_vec())
        );
    }

    #[test]
    fn test_kitty_function_keys_with_modifiers() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES;

        // F1-F4: SS3 → CSI with modifier
        let shift_f1 = Keystroke::parse("shift-f1").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_f1, mode),
            Some(b"\x1b[1;2P".to_vec())
        );

        let ctrl_f4 = Keystroke::parse("ctrl-f4").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_f4, mode),
            Some(b"\x1b[1;5S".to_vec())
        );

        // F5-F12: tilde format with modifier
        let ctrl_f5 = Keystroke::parse("ctrl-f5").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_f5, mode),
            Some(b"\x1b[15;5~".to_vec())
        );

        let shift_f12 = Keystroke::parse("shift-f12").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_f12, mode),
            Some(b"\x1b[24;2~".to_vec())
        );
    }

    #[test]
    fn test_kitty_regular_chars_disambiguate() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES;

        // Unmodified chars in level 1 use legacy
        let a = Keystroke::parse("a").unwrap();
        assert_eq!(keystroke_to_bytes(&a, mode), Some(b"a".to_vec()));

        // Ctrl+letter uses CSI-u (not raw control char)
        let ctrl_c = Keystroke::parse("ctrl-c").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_c, mode),
            Some(b"\x1b[99;5u".to_vec())
        );

        let ctrl_a = Keystroke::parse("ctrl-a").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_a, mode),
            Some(b"\x1b[97;5u".to_vec())
        );

        // Alt+letter uses CSI-u (not ESC prefix)
        let alt_a = Keystroke::parse("alt-a").unwrap();
        assert_eq!(
            keystroke_to_bytes(&alt_a, mode),
            Some(b"\x1b[97;3u".to_vec())
        );

        // Shift+letter in disambiguate mode is unambiguous. Falls through to
        // legacy encoding which produces the uppercase character, not CSI-u.
        let shift_a = Keystroke::parse("shift-a").unwrap();
        assert_eq!(keystroke_to_bytes(&shift_a, mode), Some(b"A".to_vec()));

        // Ctrl+Shift still needs CSI-u for disambiguation
        let ctrl_shift_a = Keystroke::parse("ctrl-shift-a").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_shift_a, mode),
            Some(b"\x1b[97;6u".to_vec())
        );
    }

    #[test]
    fn test_kitty_regular_chars_all_keys() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_ALL_KEYS_AS_ESC;

        // In level 4, even unmodified chars get CSI-u
        let a = Keystroke::parse("a").unwrap();
        assert_eq!(keystroke_to_bytes(&a, mode), Some(b"\x1b[97u".to_vec()));

        let one = Keystroke::parse("1").unwrap();
        assert_eq!(keystroke_to_bytes(&one, mode), Some(b"\x1b[49u".to_vec()));

        let zero = Keystroke::parse("0").unwrap();
        assert_eq!(keystroke_to_bytes(&zero, mode), Some(b"\x1b[48u".to_vec()));

        // Modified chars in level 4
        let ctrl_c = Keystroke::parse("ctrl-c").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_c, mode),
            Some(b"\x1b[99;5u".to_vec())
        );
    }

    #[test]
    fn test_kitty_all_keys_without_disambiguate() {
        // REPORT_ALL_KEYS_AS_ESC alone (without DISAMBIGUATE) should still encode
        let mode = TermMode::REPORT_ALL_KEYS_AS_ESC;

        let a = Keystroke::parse("a").unwrap();
        assert_eq!(keystroke_to_bytes(&a, mode), Some(b"\x1b[97u".to_vec()));

        let enter = Keystroke::parse("enter").unwrap();
        assert_eq!(keystroke_to_bytes(&enter, mode), Some(b"\x1b[13u".to_vec()));

        let ctrl_c = Keystroke::parse("ctrl-c").unwrap();
        assert_eq!(
            keystroke_to_bytes(&ctrl_c, mode),
            Some(b"\x1b[99;5u".to_vec())
        );
    }

    #[test]
    fn test_kitty_app_cursor_interaction() {
        // Kitty + APP_CURSOR + no mods → APP_CURSOR applies (SS3)
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::APP_CURSOR;
        let up = Keystroke::parse("up").unwrap();
        assert_eq!(keystroke_to_bytes(&up, mode), Some(b"\x1bOA".to_vec()));

        // Kitty + APP_CURSOR + Shift → Kitty modifier format overrides APP_CURSOR
        let shift_up = Keystroke::parse("shift-up").unwrap();
        assert_eq!(
            keystroke_to_bytes(&shift_up, mode),
            Some(b"\x1b[1;2A".to_vec())
        );
    }

    // -----------------------------------------------------------------------
    // REPORT_EVENT_TYPES tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_event_type_text_key_stays_utf8() {
        // DISAMBIGUATE + EVENT_TYPES: text keys stay plain UTF-8.
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_EVENT_TYPES;
        let ks = Keystroke::parse("a").unwrap();

        // Press → plain 'a'
        let press = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&press, mode), Some(b"a".to_vec()));

        // Repeat → still plain 'a' (re-sends the byte)
        let repeat = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&repeat, mode), Some(b"a".to_vec()));

        // Release → None (can't annotate plain UTF-8)
        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&release, mode), None);
    }

    #[test]
    fn test_event_type_text_key_with_all_keys() {
        // ALL_KEYS + EVENT_TYPES: text keys get CSI-u with event annotations.
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_EVENT_TYPES
            | TermMode::REPORT_ALL_KEYS_AS_ESC;
        let ks = Keystroke::parse("a").unwrap();

        // Press → CSI-u (event_type omitted for press)
        let press = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&press, mode), Some(b"\x1b[97u".to_vec()));

        // Repeat → CSI-u with :2
        let repeat = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&repeat, mode),
            Some(b"\x1b[97;1:2u".to_vec())
        );

        // Release → CSI-u with :3
        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&release, mode),
            Some(b"\x1b[97;1:3u".to_vec())
        );
    }

    #[test]
    fn test_event_type_escape_encoded_key() {
        // Ctrl+a is escape-encoded in DISAMBIGUATE mode. Gets event annotations.
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_EVENT_TYPES;
        let ks = Keystroke::parse("ctrl-c").unwrap();

        // Press → CSI-u (no event annotation)
        let press = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&press, mode),
            Some(b"\x1b[99;5u".to_vec())
        );

        // Repeat → CSI-u with :2
        let repeat = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&repeat, mode),
            Some(b"\x1b[99;5:2u".to_vec())
        );

        // Release → CSI-u with :3
        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&release, mode),
            Some(b"\x1b[99;5:3u".to_vec())
        );
    }

    #[test]
    fn test_event_type_functional_key() {
        // Functional keys (arrows) are CSI sequences. Get event annotations
        // even without keyboard modifiers.
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_EVENT_TYPES;
        let ks = Keystroke::parse("up").unwrap();

        // Press → legacy \x1b[A (no annotation needed)
        let press = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&press, mode), Some(b"\x1b[A".to_vec()));

        // Repeat → modified form with :2
        let repeat = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&repeat, mode),
            Some(b"\x1b[1;1:2A".to_vec())
        );

        // Release → modified form with :3
        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&release, mode),
            Some(b"\x1b[1;1:3A".to_vec())
        );
    }

    #[test]
    fn test_event_type_functional_with_mods() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_EVENT_TYPES;
        let ks = Keystroke::parse("shift-up").unwrap();

        // Shift+Up release → \x1b[1;2:3A
        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&release, mode),
            Some(b"\x1b[1;2:3A".to_vec())
        );
    }

    #[test]
    fn test_event_type_tilde_key() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_EVENT_TYPES;
        let ks = Keystroke::parse("pageup").unwrap();

        // PageUp release → \x1b[5;1:3~
        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&release, mode),
            Some(b"\x1b[5;1:3~".to_vec())
        );
    }

    #[test]
    fn test_event_type_ignored_without_flag() {
        // Without REPORT_EVENT_TYPES, Repeat is treated as Press and Release → None.
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_ALL_KEYS_AS_ESC;
        let ks = Keystroke::parse("a").unwrap();

        let repeat = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: None,
        };
        // Treated as press → \x1b[97u
        assert_eq!(
            key_input_to_bytes(&repeat, mode),
            Some(b"\x1b[97u".to_vec())
        );

        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&release, mode), None);
    }

    #[test]
    fn test_event_type_special_key_enter() {
        // Enter in DISAMBIGUATE + EVENT_TYPES (without ALL_KEYS): stays legacy \r.
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_EVENT_TYPES;
        let ks = Keystroke::parse("enter").unwrap();

        let repeat = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&repeat, mode), Some(b"\r".to_vec()));

        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(key_input_to_bytes(&release, mode), None);

        // With ALL_KEYS: Enter gets CSI-u with event annotations.
        let mode_all = mode | TermMode::REPORT_ALL_KEYS_AS_ESC;
        let repeat_all = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&repeat_all, mode_all),
            Some(b"\x1b[13;1:2u".to_vec())
        );

        let release_all = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: None,
        };
        assert_eq!(
            key_input_to_bytes(&release_all, mode_all),
            Some(b"\x1b[13;1:3u".to_vec())
        );
    }

    // -----------------------------------------------------------------------
    // REPORT_ASSOCIATED_TEXT tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_associated_text_simple() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_ALL_KEYS_AS_ESC
            | TermMode::REPORT_ASSOCIATED_TEXT;
        let ks = Keystroke::parse("a").unwrap();

        let input = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: Some("a"),
        };
        // \x1b[97;;97u. Empty modifier param (mods=0 but text forces it), text=97
        assert_eq!(
            key_input_to_bytes(&input, mode),
            Some(b"\x1b[97;;97u".to_vec())
        );
    }

    #[test]
    fn test_associated_text_with_mods() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_ALL_KEYS_AS_ESC
            | TermMode::REPORT_ASSOCIATED_TEXT;
        let ks = Keystroke::parse("shift-a").unwrap();

        let input = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: Some("A"),
        };
        // \x1b[97;2;65u. shift=1→mods+1=2, text='A'=65
        assert_eq!(
            key_input_to_bytes(&input, mode),
            Some(b"\x1b[97;2;65u".to_vec())
        );
    }

    #[test]
    fn test_associated_text_unicode() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_ALL_KEYS_AS_ESC
            | TermMode::REPORT_ASSOCIATED_TEXT;
        let ks = Keystroke::parse("a").unwrap();

        // Simulate a layout producing 'ä' (U+00E4 = 228)
        let input = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: Some("ä"),
        };
        assert_eq!(
            key_input_to_bytes(&input, mode),
            Some(b"\x1b[97;;228u".to_vec())
        );
    }

    #[test]
    fn test_associated_text_ignored_without_flag() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_ALL_KEYS_AS_ESC;
        // No REPORT_ASSOCIATED_TEXT
        let ks = Keystroke::parse("a").unwrap();

        let input = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: Some("a"),
        };
        // Text should NOT be included
        assert_eq!(key_input_to_bytes(&input, mode), Some(b"\x1b[97u".to_vec()));
    }

    #[test]
    fn test_associated_text_not_on_release() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_ALL_KEYS_AS_ESC
            | TermMode::REPORT_EVENT_TYPES
            | TermMode::REPORT_ASSOCIATED_TEXT;
        let ks = Keystroke::parse("a").unwrap();

        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: Some("a"),
        };
        // Release events never include text
        assert_eq!(
            key_input_to_bytes(&release, mode),
            Some(b"\x1b[97;1:3u".to_vec())
        );
    }

    // -----------------------------------------------------------------------
    // Unicode CSI-u tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_unicode_csi_u_encoding() {
        // encode_csi_u_full directly with non-ASCII codepoint
        let bytes = encode_csi_u_full(0x00F1, 0, None, None); // ñ = 241
        assert_eq!(bytes, b"\x1b[241u".to_vec());

        let bytes = encode_csi_u_full(0x00E4, 2, None, None); // ä with shift
        assert_eq!(bytes, b"\x1b[228;3u".to_vec());
    }

    // -----------------------------------------------------------------------
    // Modifier key encoding tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_modifier_key_press() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_EVENT_TYPES
            | TermMode::REPORT_ALL_KEYS_AS_ESC;

        // Shift press: codepoint=57441, mods=shift(1)→mods+1=2, press omitted
        let bytes = modifier_key_to_bytes(KITTY_LEFT_SHIFT, 1, KeyEventType::Press, mode);
        assert_eq!(bytes, Some(b"\x1b[57441;2u".to_vec()));
    }

    #[test]
    fn test_modifier_key_release() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_EVENT_TYPES
            | TermMode::REPORT_ALL_KEYS_AS_ESC;

        // Shift release: after releasing, mods=0 → mods+1=1, event_type=3
        let bytes = modifier_key_to_bytes(KITTY_LEFT_SHIFT, 0, KeyEventType::Release, mode);
        assert_eq!(bytes, Some(b"\x1b[57441;1:3u".to_vec()));
    }

    #[test]
    fn test_modifier_key_without_event_types() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES | TermMode::REPORT_ALL_KEYS_AS_ESC;
        // Without REPORT_EVENT_TYPES, modifier_key_to_bytes returns None
        let bytes = modifier_key_to_bytes(KITTY_LEFT_SHIFT, 1, KeyEventType::Press, mode);
        assert_eq!(bytes, None);
    }

    // -----------------------------------------------------------------------
    // Combined modes tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_all_modes_combined() {
        let mode = TermMode::DISAMBIGUATE_ESC_CODES
            | TermMode::REPORT_EVENT_TYPES
            | TermMode::REPORT_ALL_KEYS_AS_ESC
            | TermMode::REPORT_ASSOCIATED_TEXT;
        let ks = Keystroke::parse("a").unwrap();

        // Press with text
        let press = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Press,
            associated_text: Some("a"),
        };
        assert_eq!(
            key_input_to_bytes(&press, mode),
            Some(b"\x1b[97;;97u".to_vec())
        );

        // Repeat with text
        let repeat = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Repeat,
            associated_text: Some("a"),
        };
        assert_eq!(
            key_input_to_bytes(&repeat, mode),
            Some(b"\x1b[97;1:2;97u".to_vec())
        );

        // Release. No text
        let release = KeyInput {
            keystroke: &ks,
            event_type: KeyEventType::Release,
            associated_text: Some("a"),
        };
        assert_eq!(
            key_input_to_bytes(&release, mode),
            Some(b"\x1b[97;1:3u".to_vec())
        );
    }
}
